### ISSUE TITLE
License

### ISSUE THREAD

**Issue by giuschio** [awesomebytes/occupancy_grid_python#2]
Hello! I have noticed that there is no explicit license on your repository other than the "BSD" tag in the ROS package.xml, which is not clear. Could you add a proper license statement to the repo (e.g. using github's inbuilt tool)? It would really help people who may want to develop using this code.
Thank you for your time.

**Comment by awesomebytes** [comment]
Ages old question, but it's stated as BSD in the tag like any other ROS package. I believe it to be sufficient. Have a nice day!
